name: PHP Composer

#whenever master has a PR or is pushed to
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-18.04
    strategy:
      #for each of the following versions of PHP, with and without --prefer-lowest
      matrix:
        php-versions: ['']
        laravel-versions: ['']
        composer-options: ['', '--prefer-lowest']
        include:
          - php-versions: '5.5'
            laravel-versions: '5.1.*'
          - php-versions: '7.0'
            laravel-versions: '5.5.*'
    #set the name for each job
    name: PHP ${{ matrix.php-versions }} ${{ matrix.composer-options }}
    #set up environment variables used by unit tests
    env:
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
      AWS_CSM_ENABLED: false
    steps:
      #sets up the correct version of PHP with necessary config options
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: memory_limit=4G, phar.readonly=false

      #checkout the codebase from github
      - name: Checkout codebase
        uses: actions/checkout@v3

      #find composer
      - name: Find Composer
        run: which composer

      #remove laravel
      - name: Remove laravel
        run: |
          composer remove laravel/framework
          rm composer.lock

      #require laravel
      - name: require laravel
        run: composer require laravel/framework:${{ matrix.laravel-versions }} --no-interaction --prefer-dist ${{ matrix.composer-options }}

      #run tests
      - name: Run test suite
        run: vendor/bin/phpunit

      #remove laravel
      - name: Remove laravel
        run: |
          composer remove laravel/framework
          rm composer.lock

      #require lumen
      - name: require laravel
        run: composer require laravel/lumen-framework:5.1.* --no-interaction --prefer-dist ${{ matrix.composer-options }}

      #run tests
      - name: Run test suite
        run: vendor/bin/phpunit
